import fs from "node:fs/promises";
import { CollectionView } from "./types";

/**
 * Loads the serialized collection view generated by `mlg view`.
 *
 * The Rust process passes the JSON path through `MLG_VIEW_DATA_PATH` so the
 * Next.js app can stay stateless and render whichever temporary payload the CLI
 * created for this viewer session.
 */
export async function loadCollectionView(): Promise<CollectionView> {
  const dataPath = process.env.MLG_VIEW_DATA_PATH;

  if (!dataPath) {
    throw new Error("MLG_VIEW_DATA_PATH is not set");
  }

  const json = await fs.readFile(dataPath, "utf8");
  return JSON.parse(json) as CollectionView;
}

/** Returns true when Next is building the static export viewer. */
export function isStaticExportBuild(): boolean {
  return process.env.MLG_STATIC_EXPORT === "1";
}
