//! Renders the extracted models as markdown.
//!
//! Output is deterministic — every list is sorted and nothing depends on ambient
//! state — so the check test can compare a fresh render byte-for-byte against the
//! committed documents.

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write;

use super::formulation::Formulation;
use super::lalrpop::Grammar;
use super::model::{HeadingKind, ResolvedGroup};
use super::structural::Structural;

const BANNER: &str = "<!-- @generated by `cargo run --example gen_syntax_docs` — DO NOT EDIT BY HAND. -->";

pub fn readme() -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{BANNER}");
    let _ = writeln!(
        out,
        r#"
# Generated syntax reference

These documents are generated from the implementation sources by an internal tool.
They describe the syntax the code actually accepts, so the code stays the single
source of truth and these files cannot drift from it.

**Do not edit these files.** Change the implementation, then regenerate.

## Commands

```sh
cargo run --example gen_syntax_docs      # regenerate
cargo run --example gen_syntax_docs -- --check   # fail if stale
cargo test --test syntax_docs            # same check, wired into the test suite
```

## Files

| File | Generated from |
| --- | --- |
| [structural_syntax.md](structural_syntax.md) | `src/frontend/structural/ast.rs`, `src/frontend/structural/parser.rs` |
| [formulation_syntax.md](formulation_syntax.md) | `src/frontend/formulation/ast.rs`, `src/frontend/formulation/parser.rs`, `src/frontend/formulation/grammar.lalrpop` |

## How each fact is derived

The generator never guesses. If a fact cannot be read out of the code it fails
rather than emitting something plausible.

- **Which sections a group accepts, in what order, and which are optional** comes from
  the `identify_sections(head, .., &["Head", "given?", ..])` call in that group's parse
  function. A `?` suffix marks an optional section.
- **What a section holds** comes from the section macro in the structural AST:
  `argument_section!` is one value, `arguments_section!` is `+`, and
  `zero_or_more_arguments_section!` is `*`.
- **Which field backs a section** is read from the parse function's own construction, so
  a field whose name differs from its label is still reported correctly.
- **What heading a group takes** comes from the heading helper its parse function calls
  (`parse_required_command_heading`, `parse_optional_label_heading`, and so on).
- **Formulation surface syntax** comes from the productions in `grammar.lalrpop`; the
  **headers and statements** come from the public `parse_*` entry points of
  `formulation/parser.rs`, which parse them by hand; **node shapes** come from the
  formulation AST.

## What is checked while generating

These are the invariants that make a stale or wrong document impossible rather than
merely unlikely. Each one fails generation:

- A section optional in the parser but required in the AST, or the reverse (single-shape
  groups only — where optional sections select between shapes, the two differ by design).
- A `*Group` in the AST that no parse function was matched to, so it would silently go
  undocumented.
- An AST field that no section label fills.
- A group parsed by bespoke logic is **not** guessed at; it is listed under
  "Groups this tool cannot derive" instead.

## Caveat

A section's element type is reported as the type the AST stores. The parser may accept
a narrower form than that type can represent — for example `given:` stores a
`DeclarationStatement` but is parsed with the *refined* declaration subparser. Where the
two differ, the parse function is authoritative.
"#
    );
    out
}

// ===============================[ structural ]=====================================

pub fn structural(model: &Structural) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{BANNER}");
    let _ = writeln!(out, "\n# Structural syntax (generated)\n");
    let _ = writeln!(
        out,
        "Generated from `src/frontend/structural/ast.rs` and \
         `src/frontend/structural/parser.rs`. See [README.md](README.md).\n"
    );

    let _ = writeln!(out, "## Notation\n");
    let _ = writeln!(out, "- `X` — exactly one value in the section.");
    let _ = writeln!(out, "- `X+` — one or more values in the section.");
    let _ = writeln!(out, "- `X*` — zero or more values in the section.");
    let _ = writeln!(
        out,
        "- `section?:` — the section itself may be omitted; sections appear in the order shown."
    );
    let _ = writeln!(
        out,
        "- A leading `[..]` line is the group's heading; `[..]?` means the heading is optional."
    );
    let _ = writeln!(
        out,
        "- A section shown with no type takes no value (for example a head section \
         whose name lives in `Documented:` `called:`).\n"
    );

    let top_level: Vec<&ResolvedGroup> = model
        .groups
        .iter()
        .filter(|group| is_top_level(model, &group.group_types))
        .collect();

    let _ = writeln!(out, "## Top-level items\n");
    let _ = writeln!(out, "The {} groups accepted at the top level of a file.\n", top_level.len());
    let _ = writeln!(out, "| Head | Group | Heading |");
    let _ = writeln!(out, "| --- | --- | --- |");
    for group in &top_level {
        let _ = writeln!(
            out,
            "| `{}:` | {} | {} |",
            group.head_label,
            types_cell(&group.group_types),
            heading_cell(group.heading)
        );
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Groups\n");
    let _ = writeln!(
        out,
        "Every group the structural parser builds, including clause and item groups.\n"
    );
    for group in &model.groups {
        let _ = writeln!(out, "### `{}:`\n", group.head_label);
        if group.group_types.len() > 1 {
            // The optional sections choose the shape, so say so rather than implying
            // every listed type accepts every section.
            let _ = writeln!(
                out,
                "Builds {} — which one depends on the optional sections present.\n",
                types_cell(&group.group_types)
            );
        } else {
            let _ = writeln!(out, "Builds {}.\n", types_cell(&group.group_types));
        }
        let _ = writeln!(out, "```group");
        let _ = write!(out, "{}", group_block(group));
        let _ = writeln!(out, "```\n");
    }

    if !model.underivable.is_empty() {
        let _ = writeln!(out, "## Groups this tool cannot derive\n");
        let _ = writeln!(
            out,
            "These groups are parsed by bespoke logic rather than the \
             `identify_sections(head, .., &[..])` pattern every other group follows, so their \
             shape cannot be read out of the code. They are listed here instead of being \
             guessed at. Consult the parser directly, or refactor them onto the common \
             pattern to have them documented automatically.\n"
        );
        for group in &model.underivable {
            let _ = writeln!(
                out,
                "- {} — parsed by `{}`",
                types_cell(&group.types),
                group.parse_fn
            );
        }
        let _ = writeln!(out);
    }

    let _ = writeln!(out, "## Unions\n");
    let _ = writeln!(
        out,
        "Enums in the structural AST. Each alternative is the type it holds.\n"
    );
    for def in &model.enums {
        let _ = writeln!(out, "```union");
        let _ = writeln!(out, "{} ::=", def.name);
        for variant in &def.variants {
            match &variant.payload {
                Some(payload) => {
                    let _ = writeln!(out, "    | {payload}");
                }
                None => {
                    let _ = writeln!(out, "    | {}", variant.name);
                }
            }
        }
        let _ = writeln!(out, "```\n");
    }

    let _ = writeln!(out, "## Section catalog\n");
    let _ = writeln!(
        out,
        "Every section type and what it holds, from the section macros in the structural AST.\n"
    );
    let _ = writeln!(out, "| Section type | Holds |");
    let _ = writeln!(out, "| --- | --- |");
    for section in &model.sections {
        let _ = writeln!(
            out,
            "| `{}` | `{}{}` |",
            section.type_name,
            section.element,
            section.arity.suffix()
        );
    }

    out
}

/// Renders the `group` fence body for one group.
fn group_block(group: &ResolvedGroup) -> String {
    let mut out = String::new();
    if group.heading != HeadingKind::None {
        let _ = writeln!(out, "{}", group.heading);
    }
    for section in &group.sections {
        let optional = if section.optional { "?" } else { "" };
        match (&section.element, section.arity) {
            (Some(element), Some(arity)) => {
                let _ = writeln!(
                    out,
                    "{}{}: <{}>{}",
                    section.label,
                    optional,
                    element,
                    arity.suffix()
                );
            }
            _ => {
                let _ = writeln!(out, "{}{}:", section.label, optional);
            }
        }
    }
    out
}

fn heading_cell(kind: HeadingKind) -> String {
    match kind {
        HeadingKind::None => "none".to_owned(),
        other => format!("`{other}`"),
    }
}

/// Renders the AST types a syntax builds, joined with `or` when there are several.
fn types_cell(types: &[String]) -> String {
    types
        .iter()
        .map(|name| format!("`{name}`"))
        .collect::<Vec<_>>()
        .join(" or ")
}

/// True when any of the group's types is a variant of the `TopLevelItem` union.
fn is_top_level(model: &Structural, group_types: &[String]) -> bool {
    model
        .enums
        .iter()
        .find(|def| def.name == "TopLevelItem")
        .is_some_and(|def| {
            def.variants.iter().any(|variant| {
                variant
                    .payload
                    .as_ref()
                    .is_some_and(|payload| group_types.contains(payload))
            })
        })
}

// ===============================[ formulation ]=====================================

pub fn formulation(model: &Formulation, grammar: &Grammar) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "{BANNER}");
    let _ = writeln!(out, "\n# Formulation syntax (generated)\n");
    let _ = writeln!(
        out,
        "Generated from `src/frontend/formulation/grammar.lalrpop` (surface syntax) and \
         `src/frontend/formulation/ast.rs` (node shapes). See [README.md](README.md).\n"
    );

    let _ = writeln!(out, "## How this layer is parsed\n");
    let _ = writeln!(
        out,
        "The formulation layer has two parsers, and which one handles a construct \
         determines where its syntax is defined:\n"
    );
    let _ = writeln!(
        out,
        "1. **The LALRPOP grammar** (`grammar.lalrpop`) parses expressions and \
         forms/declarations. Its productions are listed below."
    );
    let _ = writeln!(
        out,
        "2. **A hand-written parser** (`formulation/parser.rs`) parses the headers and \
         statements, calling into the grammar for the expressions inside them. These have \
         no production, so the entry-point table below is the reference for them.\n"
    );

    let _ = writeln!(out, "## Entry points\n");
    let _ = writeln!(
        out,
        "The public `parse_*` functions of `formulation/parser.rs`. The structural parser \
         calls these to turn a section's text into a node, so these types are exactly the \
         ones the structural syntax refers to.\n"
    );
    let _ = writeln!(out, "| Entry point | Produces |");
    let _ = writeln!(out, "| --- | --- |");
    for entry in &model.entries {
        let _ = writeln!(out, "| `{}` | `{}` |", entry.name, entry.result_type);
    }
    let _ = writeln!(out);

    let grammar_entries: Vec<_> = grammar.nonterminals.iter().filter(|n| n.public).collect();
    let _ = writeln!(
        out,
        "The hand-written parser reaches the grammar through its `pub` nonterminals:\n"
    );
    for entry in &grammar_entries {
        let _ = writeln!(out, "- `{}` → `{}`", entry.name, entry.result_type);
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Terminals\n");
    let _ = writeln!(
        out,
        "The token vocabulary, from the grammar's `extern {{ enum Token {{ .. }} }}` block. \
         The left column is the terminal as written in a production.\n"
    );
    let _ = writeln!(out, "| Terminal | Token | Payload |");
    let _ = writeln!(out, "| --- | --- | --- |");
    let mut terminals = grammar.terminals.clone();
    terminals.sort_by(|a, b| a.variant.cmp(&b.variant));
    for terminal in &terminals {
        let _ = writeln!(
            out,
            "| `\"{}\"` | `{}` | {} |",
            escape_pipe(&terminal.name),
            terminal.variant,
            terminal
                .payload
                .as_ref()
                .map(|p| format!("`{p}`"))
                .unwrap_or_else(|| "—".to_owned())
        );
    }
    let _ = writeln!(out);

    let _ = writeln!(out, "## Productions\n");
    let _ = writeln!(
        out,
        "Every nonterminal, with its Rust action code stripped. `->` names the type the \
         production builds.\n"
    );
    let mut nonterminals = grammar.nonterminals.clone();
    nonterminals.sort_by(|a, b| a.name.cmp(&b.name));
    for nonterminal in &nonterminals {
        let visibility = if nonterminal.public { "pub " } else { "" };
        let _ = writeln!(out, "### `{}`\n", nonterminal.name);
        let _ = writeln!(
            out,
            "{}`{}` → `{}`\n",
            visibility, nonterminal.name, nonterminal.result_type
        );
        let _ = writeln!(out, "```production");
        let _ = writeln!(out, "{} ::=", nonterminal.name);
        for production in &nonterminal.productions {
            let symbols = if production.symbols.is_empty() {
                "ε".to_owned()
            } else {
                production.symbols.join(" ")
            };
            let _ = writeln!(out, "    | {symbols}");
        }
        let _ = writeln!(out, "```\n");
    }

    let _ = writeln!(out, "## AST nodes\n");
    let _ = writeln!(
        out,
        "The shapes the formulation AST can represent, from `formulation/ast.rs`.\n"
    );
    for def in &model.enums {
        let _ = writeln!(out, "```union");
        let _ = writeln!(out, "{} ::=", def.name);
        for variant in &def.variants {
            match &variant.payload {
                Some(payload) => {
                    let _ = writeln!(out, "    | {} ({payload})", variant.name);
                }
                None => {
                    let _ = writeln!(out, "    | {}", variant.name);
                }
            }
        }
        let _ = writeln!(out, "```\n");
    }
    let _ = writeln!(out, "### Node fields\n");
    let _ = writeln!(out, "| Node | Field | Type |");
    let _ = writeln!(out, "| --- | --- | --- |");
    for def in &model.structs {
        if def.fields.is_empty() {
            let _ = writeln!(out, "| `{}` | — | — |", def.name);
            continue;
        }
        for (index, field) in def.fields.iter().enumerate() {
            let name = if index == 0 {
                format!("`{}`", def.name)
            } else {
                String::new()
            };
            let _ = writeln!(
                out,
                "| {} | `{}` | `{}` |",
                name,
                field.name,
                escape_pipe(&field.type_text)
            );
        }
    }
    let _ = writeln!(out);

    let _ = write!(out, "{}", cross_reference(model, grammar));
    out
}

/// Reports how the grammar, the hand-written parser, and the AST line up, so drift
/// between the three is visible.
fn cross_reference(model: &Formulation, grammar: &Grammar) -> String {
    let mut out = String::new();
    let _ = writeln!(out, "## Grammar/AST cross-reference\n");
    let _ = writeln!(
        out,
        "Every nonterminal declares the AST type it builds, and every entry point declares \
         the type it returns. Pairing those against the AST shows how each node is reachable \
         — and surfaces anything that has drifted.\n"
    );

    // AST type -> the nonterminals that build it.
    let mut builders: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for nonterminal in &grammar.nonterminals {
        if let Some(ast_type) = &nonterminal.result_ast_type {
            builders
                .entry(ast_type.clone())
                .or_default()
                .insert(nonterminal.name.clone());
        }
    }
    // AST type -> the hand-written entry points that return it.
    let mut parsed: BTreeMap<String, BTreeSet<String>> = BTreeMap::new();
    for entry in &model.entries {
        parsed
            .entry(entry.result_type.clone())
            .or_default()
            .insert(entry.name.clone());
    }

    let ast_types: BTreeSet<String> = model
        .structs
        .iter()
        .map(|s| s.name.clone())
        .chain(model.enums.iter().map(|e| e.name.clone()))
        .collect();

    let reachable: BTreeSet<&String> = builders.keys().chain(parsed.keys()).collect();

    let _ = writeln!(out, "| AST type | Grammar productions | Entry points |");
    let _ = writeln!(out, "| --- | --- | --- |");
    for ast_type in &reachable {
        let _ = writeln!(
            out,
            "| `{}` | {} | {} |",
            ast_type,
            names_cell(builders.get(*ast_type)),
            names_cell(parsed.get(*ast_type))
        );
    }
    let _ = writeln!(out);

    let unbuilt: Vec<&String> = ast_types
        .iter()
        .filter(|name| !reachable.contains(*name))
        .collect();
    let _ = writeln!(out, "### Nodes with no production and no entry point\n");
    let _ = writeln!(
        out,
        "Expected for nested and helper types: they are built inside another production's \
         action code, or by a private helper, rather than being produced directly. A node \
         here is only a problem if you expected it to be parseable on its own.\n"
    );
    if unbuilt.is_empty() {
        let _ = writeln!(out, "_None._\n");
    } else {
        for name in unbuilt {
            let _ = writeln!(out, "- `{name}`");
        }
        let _ = writeln!(out);
    }

    let missing: Vec<&String> = reachable
        .iter()
        .filter(|name| !ast_types.contains(**name))
        .copied()
        .collect();
    let _ = writeln!(
        out,
        "### Types the grammar or an entry point names that the AST does not define\n"
    );
    let _ = writeln!(
        out,
        "This list must stay empty. An entry means the grammar, the parser, and the AST \
         have drifted apart.\n"
    );
    if missing.is_empty() {
        let _ = writeln!(out, "_None._");
    } else {
        for name in missing {
            let _ = writeln!(out, "- `{name}`");
        }
    }

    out
}

/// Renders a set of names as a table cell, or an em dash when there are none.
fn names_cell(names: Option<&BTreeSet<String>>) -> String {
    match names {
        Some(names) if !names.is_empty() => names
            .iter()
            .map(|n| format!("`{n}`"))
            .collect::<Vec<_>>()
            .join(", "),
        _ => "—".to_owned(),
    }
}

/// Escapes `|` so it cannot break out of a markdown table cell.
fn escape_pipe(text: &str) -> String {
    text.replace('|', "\\|")
}
