use std::fmt;

use lalrpop_util::ParseError as LalrpopParseError;

use super::ast::{
    AuthorHeader, Chain, ChainPart, CommandExpressionTailPart, CommandHeader, CommandHeaderNode,
    CommandHeaderTailPart, CurlyExpressionArgs, CurlyHeadingArgs, Expression, ExpressionAlias,
    ExpressionAliasLhs, ExpressionKind, FormOrDeclaration, FormOrDeclarationKind,
    InfixCommandHeader, IsOrRefinedStatementSpec, IsOrSpec, IsStatement, IsSubject, IsSubjectForm,
    IsSubjectKind, IsViaStatement, LabelHeader, Operator, ParenExpressionArgs, ParenHeadingArgs,
    Placeholder, PlaceholderForm, PlaceholderFormKind, PlaceholderSpecStatement,
    RefinedCommandExpression, RefinedCommandHeader, RefinedExpressionPart, RefinedHeaderPart,
    RefinedTail, ResourceHeader, SpecOperatorAlias, SpecSubject, SpecSubjectKind,
    SubjectSpecStatement, TupleForm, TypeExpression, WritingAlias,
};
use super::grammar;
use super::lexer::Lexer;
use super::span::Span;
use super::token::{LexicalError, Token};

/// Concrete parse error type returned by the generated LALRPOP grammar.
///
/// The public parser API wraps this in [`ParseError`] so hand-written parser
/// helpers and generated grammar failures can share one error channel.
type LalrpopError = LalrpopParseError<usize, Token, LexicalError>;

/// Error produced while parsing MathLingua formulation text.
///
/// `Grammar` carries errors emitted by the generated expression/form grammar.
/// `Custom` is used by the handwritten splitters and command parsers for syntax
/// that is easier to recognize after top-level delimiter analysis.
#[derive(Clone, Debug, PartialEq, Eq)]
pub enum ParseError {
    /// A failure reported by the generated LALRPOP parser.
    Grammar(LalrpopError),
    /// A targeted parser error generated by hand-written validation code.
    Custom(String),
}

impl ParseError {
    /// Builds a custom parse error with a human-readable message.
    ///
    /// Keeping this small constructor local avoids repeated `String` conversion
    /// noise in the parser while preserving an owned error payload.
    fn custom(message: impl Into<String>) -> Self {
        Self::Custom(message.into())
    }
}

impl fmt::Display for ParseError {
    /// Formats parse errors for user-facing diagnostics.
    ///
    /// Generated grammar errors are printed with debug formatting because the
    /// LALRPOP error type includes structured token information that is more
    /// useful than its terse display form.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Grammar(error) => write!(f, "{error:?}"),
            Self::Custom(message) => write!(f, "{message}"),
        }
    }
}

impl From<LalrpopError> for ParseError {
    /// Converts generated grammar errors into the parser's common error type.
    fn from(value: LalrpopError) -> Self {
        Self::Grammar(value)
    }
}

include!("parser/entrypoints.rs");
include!("parser/statements.rs");
include!("parser/commands.rs");
include!("parser/lists.rs");
include!("parser/scan.rs");

#[cfg(test)]
mod tests;
